export const ROUTES = {
  login: '/login',
  changePassword: '/change-password',
  overview: '/overview',
  connect: '/connect',
  products: '/products',
  warehouse: '/warehouse',
  orders: '/orders',
  shipping: '/shipping',
  customers: '/customers',
  chat: '/chat',
  analytics: '/analytics',
  aiContexts: '/ai-contexts',
  staff: '/staff',
} as const
